version: '3'

services:
  app:
    build:
      context: .
      dockerfile: image.dockerfile
      target: php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: remindme-laravel:latest
    container_name: remind-app
    ports:
      - "8000:8080"
      - 5173:5173
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    volumes:
      - app-storage:/var/www/storage
      - ./docker/entrypoint.dev.sh:/var/www/docker/entrypoint.sh
    entrypoint: /var/www/docker/entrypoint.sh
    networks:
      - remind_network

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/data-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nabitu
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - remind_network
    healthcheck:
      test: mysqladmin ping -h localhost

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "5672:5672" # Port RabbitMQ
      - "15672:15672" # Port RabbitMQ Management Web UI
    networks:
      - remind_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    healthcheck:
      test: /usr/bin/nc -v localhost 1025
      interval: 30s
    ports:
      - "48025:8025"
      - "41025:1025"
    networks:
      - remind_network

networks:
  remind_network:
    driver: bridge

volumes:
  app-storage: