version: '3'

services:
  worker:
    restart: always
    image: remindme-laravel:latest
    container_name: nabitu-worker
    command: php artisan queue:work --sleep=3 --tries=5
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    networks:
      - remind_network

networks:
  remind_network:
    driver: bridge
