name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-laravel:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./src
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./src
      run: composer install --no-interaction
    - name: Generate key
      working-directory: ./src
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./src
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      working-directory: ./src
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests Unit
      working-directory: ./src
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --testsuite=Unit
    - name: Execute tests Feature
      working-directory: ./src
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --testsuite=Feature
    
